### ISSUE TITLE
youtubedl-webui password

### ISSUE THREAD

**Issue by robflate** [PixiBixi/dockerfiles#2]
I installed the youtubedl-webui docker and when I open the `http://localhost:32770` it comes up with a screen asking for a password. What is the password?

**Comment by PixiBixi** [comment]
Mmh i guess its root :-)

**Comment by vpslinuxinstall** [comment]
how to reset the password?

**Comment by PixiBixi** [comment]
https://github.com/PixiBixi/Youtube-dl-WebUI#set-a-password
