### ISSUE TITLE
How to change H5ai index folder path

### ISSUE THREAD

**Issue by niguolaiya** [PixiBixi/dockerfiles#4]
Hi, 

   the H5ai index path should be the same with _h5ai folder, but in your docker witch is 'var/www' and I noticed that there is no _h5ai folder in the path, how to change the path?

because I am trying to update the H5ai in your docker, and after I replaced the _h5ai file, the index path is changed, that the file in var/www is not showing in my h5ai web. 

thankyou!

**Comment by PixiBixi** [comment]
Hi,

Can you show me the docker run command or your docker-compose please?

Thanks!

**Comment by niguolaiya** [comment]
i just copied your config for docker-compose 
which is 

services:

  h5ai:
    image: bixidock/h5ai
    container_name: h5ai
    restart: always
    volumes:
      - "./data:/usr/share/h5ai"

I think i might not present my question well 
here is the thing, i updated h5ai in your docker with replace _h5ai folder in usr/share/h5ai/_h5ai and then the index folder changed from var/www to usr/share/h5ai/ 
so, my question is how to change the index folder back to var/www ? or any other folder ? just like you did in your docker

Thanks

**Comment by niguolaiya** [comment]
> 
> 
> Hi,
> 
> Can you show me the docker run command or your docker-compose please?
> 
> Thanks!

i just copied your config for docker-compose
which is

services:

h5ai:
image: bixidock/h5ai
container_name: h5ai
restart: always
volumes:
- "./data:/usr/share/h5ai"

I think i might not present my question well
here is the thing, i updated h5ai in your docker with replace _h5ai folder in usr/share/h5ai/_h5ai and then the index folder changed from var/www to usr/share/h5ai/
so, my question is how to change the index folder back to var/www ? or any other folder ? just like you did in your docker

Thanks

**Comment by niguolaiya** [comment]
I saw the patch thing in the github, thankyou
